# -*- coding: utf-8 -*-
# Cadrage par domaine : intro, methode, banque de questions, conseils d'examen.
DOM = {
"AI": dict(
  key="ai", label="Intelligence Artificielle", tint="#E01D8C",
  intro="Un PFE en intelligence artificielle ne se juge pas à la sophistication du modèle mais à la qualité de la question posée et à l'honnêteté de l'évaluation. Avant toute ligne de code, il faut formuler la tâche d'apprentissage, identifier la donnée disponible et décider de la métrique qui tranchera.",
  method="La démarche attendue est celle d'une étude expérimentale : constituer un jeu de référence, établir une solution de base naïve, puis ne complexifier qu'en démontrant un gain mesuré. Chaque comparaison doit se faire à protocole constant.",
  pitfalls="Les écueils classiques sont la fuite de données entre entraînement et test, une métrique qui ne reflète pas l'usage réel, et l'absence de solution de base qui empêche de juger si le modèle apporte quoi que ce soit.",
  qbank=[
    ("Dans un PFE d'IA, à quoi sert une solution de base (baseline) naïve ?",
     "À fournir un point de comparaison sans lequel le gain du modèle ne peut pas être jugé",
     ["À accélérer l'entraînement du modèle final","À remplacer la phase d'annotation des données","À réduire la taille du jeu de test"],
     "Sans baseline, une métrique isolée ne dit pas si le modèle apporte un gain réel."),
    ("Qu'est-ce qu'une fuite de données (data leakage) ?",
     "De l'information du jeu de test qui influence l'entraînement et gonfle artificiellement les scores",
     ["Une perte de lignes lors du chargement du fichier","Un dépassement de la mémoire pendant l'entraînement","Un jeu de données trop volumineux pour le disque"],
     "La fuite produit des scores excellents en laboratoire qui s'effondrent en production."),
    ("Pourquoi figer les seeds aléatoires dans un projet d'apprentissage ?",
     "Pour rendre les résultats reproductibles et les comparaisons entre essais valides",
     ["Pour accélérer la convergence du modèle","Pour réduire le nombre de paramètres","Pour éviter le surapprentissage"],
     "Sans seeds fixes, l'écart observé entre deux essais peut n'être que du bruit."),
    ("Quand une métrique d'exactitude (accuracy) devient-elle trompeuse ?",
     "Lorsque les classes sont fortement déséquilibrées",
     ["Lorsque le jeu de données est volumineux","Lorsque le modèle est entraîné sur GPU","Lorsque les variables sont normalisées"],
     "Sur un jeu à 99 % de négatifs, prédire toujours « négatif » donne 99 % d'exactitude sans rien apprendre."),
  ],
  tips=["Présenter la solution de base avant le modèle final : le jury juge l'écart, pas le score absolu.",
        "Documenter la répartition entraînement/validation/test et prouver qu'aucune donnée ne fuit.",
        "Justifier la métrique choisie par l'usage métier, pas par sa commodité."]),
"AGENTS": dict(
  key="agents", label="AI Agents", tint="#B0177F",
  intro="Un agent est un système qui décide d'appeler des outils pour atteindre un objectif. La difficulté d'un PFE sur ce sujet n'est pas de faire répondre un modèle, mais de rendre ses décisions bornées, traçables et évaluables.",
  method="La démarche consiste à définir précisément le périmètre d'action de l'agent, la liste fermée des outils auxquels il a droit, les conditions d'arrêt, et le protocole d'évaluation sur un jeu de tâches de référence.",
  pitfalls="Les écueils récurrents sont les boucles d'appels sans condition d'arrêt, une confiance aveugle dans la sortie du modèle sans validation de schéma, et l'absence de traces qui rend tout diagnostic impossible.",
  qbank=[
    ("Pourquoi borner explicitement le nombre d'itérations d'un agent ?",
     "Parce qu'un agent sans condition d'arrêt peut boucler indéfiniment et consommer sans converger",
     ["Parce que le modèle perd en précision après dix appels","Parce que les outils externes refusent les appels répétés","Parce que la mémoire de l'agent se vide automatiquement"],
     "La condition d'arrêt est une garantie de sûreté, pas une optimisation."),
    ("À quoi sert la validation de schéma sur la sortie d'un LLM ?",
     "À rejeter les réponses malformées avant qu'elles n'atteignent le reste du système",
     ["À réduire le coût d'inférence du modèle","À améliorer la qualité du prompt automatiquement","À chiffrer les réponses produites"],
     "Un LLM produit du texte : sans validation, une sortie inattendue casse la chaîne en aval."),
    ("Que doit contenir la trace d'un appel d'agent pour être exploitable ?",
     "Le prompt, l'outil appelé, la réponse obtenue et le coût associé",
     ["Uniquement la réponse finale montrée à l'utilisateur","Uniquement la durée totale de la session","Uniquement le nom du modèle utilisé"],
     "Sans trace complète, il est impossible de rejouer et de diagnostiquer une mauvaise décision."),
    ("Pourquoi restreindre la liste des outils accessibles à un agent ?",
     "Pour limiter la surface d'action et rendre le comportement prévisible et auditable",
     ["Pour réduire la taille du contexte envoyé","Pour accélérer le chargement du modèle","Pour éviter de payer des licences d'outils"],
     "Le moindre privilège s'applique à un agent comme à un utilisateur."),
  ],
  tips=["Montrer au jury une trace complète d'exécution, pas seulement le résultat final.",
        "Présenter le jeu de tâches d'évaluation et le taux de réussite, avec les échecs analysés.",
        "Expliquer les garde-fous : périmètre des outils, conditions d'arrêt, validation des sorties."]),
"DEVOPS": dict(
  key="devops", label="DevOps", tint="#8A1B85",
  intro="Un PFE DevOps se juge sur l'automatisation effective et la fiabilité démontrée, pas sur le nombre d'outils empilés. La question centrale est : qu'est-ce qui était manuel et fragile, et qu'est-ce qui est désormais automatique et vérifiable ?",
  method="La démarche consiste à mesurer un état initial (durée de déploiement, taux d'échec, temps de rétablissement), à automatiser, puis à mesurer de nouveau. L'infrastructure et la configuration doivent être décrites dans le dépôt.",
  pitfalls="Les écueils fréquents sont l'absence de mesure avant/après, des étapes manuelles cachées qui invalident l'automatisation, et une chaîne d'intégration qui ne teste rien de significatif.",
  qbank=[
    ("Que signifie l'idempotence d'une opération de déploiement ?",
     "Rejouer l'opération plusieurs fois aboutit au même état final sans effet de bord",
     ["L'opération s'exécute plus vite à chaque passage","L'opération ne peut être lancée qu'une seule fois","L'opération se termine toujours en succès"],
     "L'idempotence est ce qui rend une automatisation sûre à relancer après un échec partiel."),
    ("Pourquoi décrire l'infrastructure comme du code ?",
     "Pour la versionner, la relire et la reconstruire à l'identique",
     ["Pour supprimer le besoin de sauvegardes","Pour réduire le coût des machines","Pour éviter d'écrire de la documentation"],
     "L'infrastructure comme code rend les changements traçables et réversibles."),
    ("À quoi sert une sonde de disponibilité (readiness probe) ?",
     "À n'envoyer du trafic à une instance que lorsqu'elle est réellement prête à le traiter",
     ["À redémarrer l'instance en cas de fuite mémoire","À mesurer la consommation CPU de l'instance","À chiffrer le trafic entrant"],
     "Sans sonde de disponibilité, du trafic est routé vers des instances encore en cours de démarrage."),
    ("Quel indicateur traduit le mieux la capacité à se remettre d'une panne ?",
     "Le temps moyen de rétablissement",
     ["Le nombre de déploiements par jour","Le nombre de lignes de configuration","La taille des images produites"],
     "Le temps de rétablissement mesure la résilience réelle, au-delà de la fréquence de livraison."),
  ],
  tips=["Chiffrer l'avant et l'après : durée, fréquence, taux d'échec, temps de rétablissement.",
        "Prouver qu'aucune étape manuelle ne subsiste en rejouant la chaîne devant le jury.",
        "Montrer un retour arrière réel, pas seulement un déploiement réussi."]),
"CYBER": dict(
  key="cyber", label="Cybersécurité", tint="#6B1E86",
  intro="Un PFE en cybersécurité s'évalue sur la rigueur du périmètre, la qualité des preuves et la pertinence des contre-mesures. Tout ce qui est testé doit l'être sur une infrastructure que l'on possède ou pour laquelle on dispose d'une autorisation écrite.",
  method="La démarche est celle du cycle défensif : modéliser la menace, instrumenter pour détecter, éprouver la détection par un scénario contrôlé, puis corriger et mesurer le gain. Chaque test est documenté avec sa date, son périmètre et son résultat.",
  pitfalls="Les écueils majeurs sont le travail hors périmètre autorisé, une détection jamais éprouvée par un scénario réel, et des rapports d'outil livrés bruts sans priorisation ni analyse d'impact.",
  qbank=[
    ("Quelle condition doit précéder tout test de sécurité offensif ?",
     "Une autorisation écrite et un périmètre explicitement délimité",
     ["Un scanner à jour de ses signatures","Un accès administrateur au poste de travail","Une connexion réseau à haut débit"],
     "Sans autorisation et périmètre écrits, le test est illégal quelle que soit l'intention."),
    ("Pourquoi éprouver une règle de détection par un scénario contrôlé ?",
     "Parce qu'une règle jamais déclenchée ne prouve rien sur sa capacité à détecter",
     ["Pour réduire le volume de journaux stockés","Pour accélérer l'indexation du SIEM","Pour diminuer le nombre d'agents déployés"],
     "Une détection non testée est une hypothèse, pas un contrôle."),
    ("Que signifie le principe du moindre privilège ?",
     "N'accorder que les droits strictement nécessaires à l'accomplissement d'une tâche",
     ["Limiter le nombre de comptes administrateurs à un seul","Changer les mots de passe tous les trente jours","Chiffrer l'intégralité des disques du parc"],
     "Le moindre privilège limite l'impact d'une compromission, quel que soit le vecteur."),
    ("Dans une investigation, pourquoi capturer la mémoire vive avant d'éteindre la machine ?",
     "Parce que la mémoire contient des traces volatiles définitivement perdues à l'extinction",
     ["Parce que le disque est chiffré et illisible à froid","Parce que la capture disque prend trop de temps","Parce que les journaux système sont incomplets"],
     "Processus en cours, connexions et clés en mémoire disparaissent à l'extinction."),
  ],
  tips=["Ouvrir le mémoire par le périmètre autorisé et la date des tests : c'est la première question du jury.",
        "Pour chaque vulnérabilité, présenter l'impact et la contre-mesure, pas seulement la détection.",
        "Montrer une détection qui se déclenche en direct plutôt qu'une capture d'écran."]),
"DATA": dict(
  key="data", label="Data Analysis", tint="#4A1A6E",
  intro="Un PFE en analyse de données se juge sur la fiabilité de la chaîne et sur la capacité à répondre à une question métier précise. Un tableau de bord élégant alimenté par des données non validées n'a aucune valeur.",
  method="La démarche part de la question métier, remonte aux sources, établit des contrôles de qualité explicites, puis construit les transformations versionnées et documentées qui mènent au résultat publié.",
  pitfalls="Les écueils habituels sont des transformations non testées, un lignage impossible à reconstituer, et des indicateurs dont la définition varie d'un tableau de bord à l'autre.",
  qbank=[
    ("Pourquoi tester les données et pas seulement le code du pipeline ?",
     "Parce qu'un code correct peut produire des résultats faux si les données d'entrée changent de forme",
     ["Parce que les tests de code sont trop lents à exécuter","Parce que le code d'un pipeline change rarement","Parce que les tests de données remplacent la documentation"],
     "Les contrôles de qualité attrapent les régressions que les tests unitaires ne voient pas."),
    ("Qu'apporte le lignage des données ?",
     "La capacité de savoir d'où vient un chiffre et ce qu'un changement amont va casser",
     ["Une réduction du volume stocké","Un chiffrement des colonnes sensibles","Une accélération des requêtes analytiques"],
     "Le lignage est ce qui permet d'analyser l'impact d'un changement de source."),
    ("Pourquoi une transformation doit-elle être idempotente ?",
     "Pour pouvoir rejouer un traitement après incident sans dupliquer ni corrompre les données",
     ["Pour réduire le temps d'exécution du traitement","Pour éviter d'indexer la table cible","Pour permettre le chiffrement au repos"],
     "Le rejeu après incident est la norme dans un pipeline planifié."),
    ("Qu'est-ce qu'une couche sémantique dans un projet analytique ?",
     "Une définition unique et partagée des indicateurs, réutilisée par tous les tableaux de bord",
     ["Une copie des données dans un format colonne","Un cache des requêtes les plus fréquentes","Un index spécialisé pour le texte"],
     "Sans définition unique, deux tableaux de bord affichent deux chiffres différents pour le même indicateur."),
  ],
  tips=["Présenter les contrôles de qualité et un cas où ils ont bloqué un lot défectueux.",
        "Montrer le lignage de bout en bout, de la source au graphique publié.",
        "Donner la définition écrite de chaque indicateur affiché."]),
}
